name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:       # allow manual runs
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Generate Snake Animation
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: roshan7600
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Deploy to Output Branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
